-- Esquema inicial del módulo `conocimiento` (segunda app del ecosistema).
--
-- Ninguna de estas tablas toca las de hábitos: son ramas independientes que
-- solo se cruzan en `usuario`. De ahí `categoria_conocimiento` en vez de
-- reutilizar `categoria`, que ya existe y es otro concepto.

CREATE TABLE categoria_conocimiento (
    categoria_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo       VARCHAR(50) UNIQUE,
    nombre       VARCHAR(100) NOT NULL,
    descripcion  VARCHAR(200),
    color        VARCHAR(50),
    icono        VARCHAR(50),
    orden        INTEGER NOT NULL
);

CREATE TABLE pildora (
    pildora_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo             VARCHAR(200) NOT NULL,
    preview_corto      VARCHAR(300) NOT NULL,
    contenido_completo TEXT NOT NULL,
    libro_origen       VARCHAR(200),
    imagen_url         VARCHAR(500),
    activa             BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion     TIMESTAMP NOT NULL
);

CREATE TABLE pildora_categoria (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pildora_id   INTEGER NOT NULL,
    categoria_id INTEGER NOT NULL,
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT FK_pildora_categoria_pildora
        FOREIGN KEY (pildora_id) REFERENCES pildora (pildora_id),
    CONSTRAINT FK_pildora_categoria_categoria
        FOREIGN KEY (categoria_id) REFERENCES categoria_conocimiento (categoria_id),
    CONSTRAINT UK_pildora_categoria UNIQUE (pildora_id, categoria_id)
);

-- Mínimo una categoría en QUIERE por usuario: eso lo valida el service, no la
-- BD. Aquí solo se impide que haya dos preferencias para la misma categoría.
CREATE TABLE usuario_categoria_preferencia (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   INTEGER NOT NULL,
    categoria_id INTEGER NOT NULL,
    estado       VARCHAR(30) NOT NULL,
    fecha        TIMESTAMP NOT NULL,
    CONSTRAINT FK_usuario_categoria_pref_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id),
    CONSTRAINT FK_usuario_categoria_pref_categoria
        FOREIGN KEY (categoria_id) REFERENCES categoria_conocimiento (categoria_id),
    CONSTRAINT UK_usuario_categoria_preferencia UNIQUE (usuario_id, categoria_id)
);

-- Una sola fila por par usuario-píldora: `num_descartes` se incrementa, no se
-- insertan filas nuevas en cada descarte.
CREATE TABLE usuario_pildora (
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id               INTEGER NOT NULL,
    pildora_id               INTEGER NOT NULL,
    estado                   VARCHAR(30) NOT NULL,
    num_descartes            INTEGER NOT NULL DEFAULT 0,
    fecha_ultima_interaccion TIMESTAMP NOT NULL,
    CONSTRAINT FK_usuario_pildora_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id),
    CONSTRAINT FK_usuario_pildora_pildora
        FOREIGN KEY (pildora_id) REFERENCES pildora (pildora_id),
    CONSTRAINT UK_usuario_pildora UNIQUE (usuario_id, pildora_id)
);

-- `nota_personal` es privada del propio usuario, no una reseña pública.
CREATE TABLE valoracion_pildora (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id    INTEGER NOT NULL,
    pildora_id    INTEGER NOT NULL,
    puntuacion    INTEGER NOT NULL,
    nota_personal VARCHAR(500),
    fecha         TIMESTAMP NOT NULL,
    CONSTRAINT FK_valoracion_pildora_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id),
    CONSTRAINT FK_valoracion_pildora_pildora
        FOREIGN KEY (pildora_id) REFERENCES pildora (pildora_id),
    CONSTRAINT UK_valoracion_pildora UNIQUE (usuario_id, pildora_id)
);
