--
-- PostgreSQL database dump
--

\restrict 3LdYODu28AMoxW9Zn2jdiDuw1S4L62f5pQiSVISxXpzIF4gz1pSmeLeDVUvd7CE

-- Dumped from database version 18.4 (Ubuntu 18.4-1.pgdg24.04+1)
-- Dumped by pg_dump version 18.4 (Ubuntu 18.4-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categoria (
    categoria_id integer NOT NULL,
    codigo character varying(50),
    color character varying(50),
    descripcion character varying(200),
    es_global boolean NOT NULL,
    icono character varying(50),
    nombre character varying(100) NOT NULL,
    orden integer,
    creador_id integer
);


--
-- Name: categoria_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categoria ALTER COLUMN categoria_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categoria_conocimiento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categoria_conocimiento (
    categoria_id integer NOT NULL,
    codigo character varying(50),
    nombre character varying(100) NOT NULL,
    descripcion character varying(200),
    color character varying(50),
    icono character varying(50),
    orden integer NOT NULL
);


--
-- Name: categoria_conocimiento_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categoria_conocimiento ALTER COLUMN categoria_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_conocimiento_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: codigo_recuperacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.codigo_recuperacion (
    codigo_id integer NOT NULL,
    codigo character varying(6) NOT NULL,
    email character varying(150) NOT NULL,
    fecha_expiracion timestamp(6) without time zone NOT NULL,
    usado boolean NOT NULL
);


--
-- Name: codigo_recuperacion_codigo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.codigo_recuperacion ALTER COLUMN codigo_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.codigo_recuperacion_codigo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: habito; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.habito (
    habito_id integer NOT NULL,
    activo boolean NOT NULL,
    descripcion character varying(500),
    dias_semana character varying(20),
    fecha_inicio date NOT NULL,
    frecuencia character varying(255) NOT NULL,
    meta integer,
    nombre character varying(100) NOT NULL,
    recordatorio_activo boolean NOT NULL,
    recordatorio_hora time(6) without time zone,
    propietario_id integer NOT NULL,
    tipo_id integer,
    CONSTRAINT habito_frecuencia_check CHECK (((frecuencia)::text = ANY ((ARRAY['DIARIO'::character varying, 'SEMANAL'::character varying])::text[])))
);


--
-- Name: habito_habito_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.habito ALTER COLUMN habito_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.habito_habito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: logro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.logro (
    logro_id integer NOT NULL,
    activo boolean NOT NULL,
    categoria character varying(50) NOT NULL,
    codigo character varying(50) NOT NULL,
    descripcion character varying(255) NOT NULL,
    icono character varying(100),
    nivel character varying(20) NOT NULL,
    nombre character varying(100) NOT NULL,
    puntos integer NOT NULL,
    origen_app character varying(30)
);


--
-- Name: logro_logro_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.logro ALTER COLUMN logro_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.logro_logro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mascota; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mascota (
    mascota_id integer NOT NULL,
    experiencia integer NOT NULL,
    fecha_ultima_comida date,
    nombre character varying(255),
    usuario_id integer NOT NULL,
    fecha_ultimo_dia_completo date
);


--
-- Name: mascota_mascota_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mascota ALTER COLUMN mascota_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mascota_mascota_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pildora; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pildora (
    pildora_id integer NOT NULL,
    titulo character varying(200) NOT NULL,
    preview_corto character varying(300) NOT NULL,
    contenido_completo text NOT NULL,
    libro_origen character varying(200),
    imagen_url character varying(500),
    activa boolean DEFAULT true NOT NULL,
    fecha_creacion timestamp without time zone NOT NULL
);


--
-- Name: pildora_categoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pildora_categoria (
    id integer NOT NULL,
    pildora_id integer NOT NULL,
    categoria_id integer NOT NULL,
    es_principal boolean DEFAULT false NOT NULL
);


--
-- Name: pildora_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pildora_categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pildora_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pildora_pildora_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pildora ALTER COLUMN pildora_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pildora_pildora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: producto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.producto (
    producto_id integer NOT NULL,
    activo boolean NOT NULL,
    categoria character varying(50) NOT NULL,
    codigo character varying(50) NOT NULL,
    descripcion character varying(255) NOT NULL,
    icono character varying(100),
    nombre character varying(100) NOT NULL,
    precio integer NOT NULL,
    tipo character varying(20) NOT NULL,
    origen_app character varying(30)
);


--
-- Name: producto_producto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.producto ALTER COLUMN producto_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: racha; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.racha (
    racha_id integer NOT NULL,
    periodo_meta_alcanzada date,
    racha_actual integer NOT NULL,
    racha_maxima integer NOT NULL,
    ultima_fecha date NOT NULL,
    habito_ref integer NOT NULL
);


--
-- Name: racha_racha_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.racha ALTER COLUMN racha_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.racha_racha_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registro (
    registro_id integer NOT NULL,
    completado boolean NOT NULL,
    fecha date NOT NULL,
    nota character varying(500),
    valoracion integer,
    habito_ref integer NOT NULL
);


--
-- Name: registro_registro_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.registro ALTER COLUMN registro_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registro_registro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario (
    usuario_id integer NOT NULL,
    contrasena character varying(255) NOT NULL,
    email character varying(150) NOT NULL,
    fcm_token character varying(255),
    fecha_registro timestamp(6) without time zone NOT NULL,
    idioma character varying(10) DEFAULT 'es'::character varying NOT NULL,
    nombre character varying(100) NOT NULL,
    proveedor_auth character varying(20) NOT NULL,
    username character varying(50) NOT NULL,
    zona_horaria character varying(64) DEFAULT 'Europe/Madrid'::character varying NOT NULL
);


--
-- Name: usuario_categoria_preferencia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario_categoria_preferencia (
    id integer NOT NULL,
    usuario_id integer NOT NULL,
    categoria_id integer NOT NULL,
    estado character varying(30) NOT NULL,
    fecha timestamp without time zone NOT NULL,
    puntuacion_afinidad double precision DEFAULT 0 NOT NULL
);


--
-- Name: usuario_categoria_preferencia_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario_categoria_preferencia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_categoria_preferencia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_logro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario_logro (
    usuario_logro_id integer NOT NULL,
    fecha_conseguido timestamp(6) without time zone NOT NULL,
    logro_id integer NOT NULL,
    usuario_id integer NOT NULL
);


--
-- Name: usuario_logro_usuario_logro_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario_logro ALTER COLUMN usuario_logro_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_logro_usuario_logro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_moneda; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario_moneda (
    movimiento_id integer NOT NULL,
    cantidad integer NOT NULL,
    descripcion character varying(255),
    fecha timestamp(6) without time zone NOT NULL,
    origen character varying(50) NOT NULL,
    referencia_id integer,
    usuario_id integer NOT NULL
);


--
-- Name: usuario_moneda_movimiento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario_moneda ALTER COLUMN movimiento_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_moneda_movimiento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_pildora; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario_pildora (
    id integer NOT NULL,
    usuario_id integer NOT NULL,
    pildora_id integer NOT NULL,
    estado character varying(30) NOT NULL,
    num_descartes integer DEFAULT 0 NOT NULL,
    fecha_ultima_interaccion timestamp without time zone NOT NULL
);


--
-- Name: usuario_pildora_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario_pildora ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_pildora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_producto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario_producto (
    usuario_producto_id integer NOT NULL,
    cantidad integer NOT NULL,
    equipado boolean NOT NULL,
    fecha_adquirido timestamp(6) without time zone NOT NULL,
    producto_id integer NOT NULL,
    usuario_id integer NOT NULL
);


--
-- Name: usuario_producto_usuario_producto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario_producto ALTER COLUMN usuario_producto_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_producto_usuario_producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario ALTER COLUMN usuario_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: valoracion_pildora; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.valoracion_pildora (
    id integer NOT NULL,
    usuario_id integer NOT NULL,
    pildora_id integer NOT NULL,
    puntuacion integer NOT NULL,
    nota_personal character varying(500),
    fecha timestamp without time zone NOT NULL
);


--
-- Name: valoracion_pildora_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.valoracion_pildora ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.valoracion_pildora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categoria_conocimiento categoria_conocimiento_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categoria_conocimiento
    ADD CONSTRAINT categoria_conocimiento_codigo_key UNIQUE (codigo);


--
-- Name: categoria_conocimiento categoria_conocimiento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categoria_conocimiento
    ADD CONSTRAINT categoria_conocimiento_pkey PRIMARY KEY (categoria_id);


--
-- Name: categoria categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT categoria_pkey PRIMARY KEY (categoria_id);


--
-- Name: codigo_recuperacion codigo_recuperacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.codigo_recuperacion
    ADD CONSTRAINT codigo_recuperacion_pkey PRIMARY KEY (codigo_id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: habito habito_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.habito
    ADD CONSTRAINT habito_pkey PRIMARY KEY (habito_id);


--
-- Name: logro logro_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logro
    ADD CONSTRAINT logro_pkey PRIMARY KEY (logro_id);


--
-- Name: mascota mascota_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mascota
    ADD CONSTRAINT mascota_pkey PRIMARY KEY (mascota_id);


--
-- Name: pildora_categoria pildora_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pildora_categoria
    ADD CONSTRAINT pildora_categoria_pkey PRIMARY KEY (id);


--
-- Name: pildora pildora_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pildora
    ADD CONSTRAINT pildora_pkey PRIMARY KEY (pildora_id);


--
-- Name: producto producto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_pkey PRIMARY KEY (producto_id);


--
-- Name: racha racha_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.racha
    ADD CONSTRAINT racha_pkey PRIMARY KEY (racha_id);


--
-- Name: registro registro_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registro
    ADD CONSTRAINT registro_pkey PRIMARY KEY (registro_id);


--
-- Name: usuario uk5171l57faosmj8myawaucatdw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk5171l57faosmj8myawaucatdw UNIQUE (email);


--
-- Name: usuario uk863n1y3x0jalatoir4325ehal; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk863n1y3x0jalatoir4325ehal UNIQUE (username);


--
-- Name: mascota uk9pvdtntgdqv7n7vbuv1cmidbk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mascota
    ADD CONSTRAINT uk9pvdtntgdqv7n7vbuv1cmidbk UNIQUE (usuario_id);


--
-- Name: pildora_categoria uk_pildora_categoria; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pildora_categoria
    ADD CONSTRAINT uk_pildora_categoria UNIQUE (pildora_id, categoria_id);


--
-- Name: usuario_categoria_preferencia uk_usuario_categoria_preferencia; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_categoria_preferencia
    ADD CONSTRAINT uk_usuario_categoria_preferencia UNIQUE (usuario_id, categoria_id);


--
-- Name: usuario_pildora uk_usuario_pildora; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_pildora
    ADD CONSTRAINT uk_usuario_pildora UNIQUE (usuario_id, pildora_id);


--
-- Name: valoracion_pildora uk_valoracion_pildora; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.valoracion_pildora
    ADD CONSTRAINT uk_valoracion_pildora UNIQUE (usuario_id, pildora_id);


--
-- Name: racha ukex265rljgta7kvfkn0luaklu1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.racha
    ADD CONSTRAINT ukex265rljgta7kvfkn0luaklu1 UNIQUE (habito_ref);


--
-- Name: categoria ukgqotsute2hs9urwkx0rxtrbb3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT ukgqotsute2hs9urwkx0rxtrbb3 UNIQUE (codigo);


--
-- Name: logro ukhb93k41jkdfcqrb3ctgaa6028; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logro
    ADD CONSTRAINT ukhb93k41jkdfcqrb3ctgaa6028 UNIQUE (codigo);


--
-- Name: producto ukkxdt4u9c4w6vveo7ylph4pd09; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT ukkxdt4u9c4w6vveo7ylph4pd09 UNIQUE (codigo);


--
-- Name: usuario_logro uq_usuario_logro; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_logro
    ADD CONSTRAINT uq_usuario_logro UNIQUE (usuario_id, logro_id);


--
-- Name: usuario_categoria_preferencia usuario_categoria_preferencia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_categoria_preferencia
    ADD CONSTRAINT usuario_categoria_preferencia_pkey PRIMARY KEY (id);


--
-- Name: usuario_logro usuario_logro_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_logro
    ADD CONSTRAINT usuario_logro_pkey PRIMARY KEY (usuario_logro_id);


--
-- Name: usuario_moneda usuario_moneda_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_moneda
    ADD CONSTRAINT usuario_moneda_pkey PRIMARY KEY (movimiento_id);


--
-- Name: usuario_pildora usuario_pildora_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_pildora
    ADD CONSTRAINT usuario_pildora_pkey PRIMARY KEY (id);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (usuario_id);


--
-- Name: usuario_producto usuario_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_producto
    ADD CONSTRAINT usuario_producto_pkey PRIMARY KEY (usuario_producto_id);


--
-- Name: valoracion_pildora valoracion_pildora_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.valoracion_pildora
    ADD CONSTRAINT valoracion_pildora_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_habito_propietario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_habito_propietario ON public.habito USING btree (propietario_id);


--
-- Name: categoria fk_categoria_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT fk_categoria_usuario FOREIGN KEY (creador_id) REFERENCES public.usuario(usuario_id);


--
-- Name: habito fk_habito_categoria; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.habito
    ADD CONSTRAINT fk_habito_categoria FOREIGN KEY (tipo_id) REFERENCES public.categoria(categoria_id);


--
-- Name: habito fk_habito_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.habito
    ADD CONSTRAINT fk_habito_usuario FOREIGN KEY (propietario_id) REFERENCES public.usuario(usuario_id);


--
-- Name: mascota fk_mascota_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mascota
    ADD CONSTRAINT fk_mascota_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(usuario_id);


--
-- Name: pildora_categoria fk_pildora_categoria_categoria; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pildora_categoria
    ADD CONSTRAINT fk_pildora_categoria_categoria FOREIGN KEY (categoria_id) REFERENCES public.categoria_conocimiento(categoria_id);


--
-- Name: pildora_categoria fk_pildora_categoria_pildora; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pildora_categoria
    ADD CONSTRAINT fk_pildora_categoria_pildora FOREIGN KEY (pildora_id) REFERENCES public.pildora(pildora_id);


--
-- Name: racha fk_racha_habito; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.racha
    ADD CONSTRAINT fk_racha_habito FOREIGN KEY (habito_ref) REFERENCES public.habito(habito_id);


--
-- Name: registro fk_registro_habito; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registro
    ADD CONSTRAINT fk_registro_habito FOREIGN KEY (habito_ref) REFERENCES public.habito(habito_id);


--
-- Name: usuario_categoria_preferencia fk_usuario_categoria_pref_categoria; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_categoria_preferencia
    ADD CONSTRAINT fk_usuario_categoria_pref_categoria FOREIGN KEY (categoria_id) REFERENCES public.categoria_conocimiento(categoria_id);


--
-- Name: usuario_categoria_preferencia fk_usuario_categoria_pref_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_categoria_preferencia
    ADD CONSTRAINT fk_usuario_categoria_pref_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(usuario_id);


--
-- Name: usuario_pildora fk_usuario_pildora_pildora; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_pildora
    ADD CONSTRAINT fk_usuario_pildora_pildora FOREIGN KEY (pildora_id) REFERENCES public.pildora(pildora_id);


--
-- Name: usuario_pildora fk_usuario_pildora_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_pildora
    ADD CONSTRAINT fk_usuario_pildora_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(usuario_id);


--
-- Name: usuario_logro fk_usuariologro_logro; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_logro
    ADD CONSTRAINT fk_usuariologro_logro FOREIGN KEY (logro_id) REFERENCES public.logro(logro_id);


--
-- Name: usuario_logro fk_usuariologro_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_logro
    ADD CONSTRAINT fk_usuariologro_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(usuario_id);


--
-- Name: usuario_moneda fk_usuariomoneda_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_moneda
    ADD CONSTRAINT fk_usuariomoneda_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(usuario_id);


--
-- Name: usuario_producto fk_usuarioproducto_producto; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_producto
    ADD CONSTRAINT fk_usuarioproducto_producto FOREIGN KEY (producto_id) REFERENCES public.producto(producto_id);


--
-- Name: usuario_producto fk_usuarioproducto_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_producto
    ADD CONSTRAINT fk_usuarioproducto_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(usuario_id);


--
-- Name: valoracion_pildora fk_valoracion_pildora_pildora; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.valoracion_pildora
    ADD CONSTRAINT fk_valoracion_pildora_pildora FOREIGN KEY (pildora_id) REFERENCES public.pildora(pildora_id);


--
-- Name: valoracion_pildora fk_valoracion_pildora_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.valoracion_pildora
    ADD CONSTRAINT fk_valoracion_pildora_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(usuario_id);


--
-- PostgreSQL database dump complete
--

\unrestrict 3LdYODu28AMoxW9Zn2jdiDuw1S4L62f5pQiSVISxXpzIF4gz1pSmeLeDVUvd7CE

